using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DatabaseController.Models
{
    /// <summary>
    /// Base representation of an object in the Navisworks model. This class can be extended to include more specific properties for different types of objects (e.g., walls, doors, etc.).
    /// </summary>
    public class ModelObject : Interfaces.IObject
    {
        [Key]
        public string Guid { get; set; } = string.Empty; // guid generated by Navisworks, used as primary key

        [Required]
        public string Name { get; set; } = string.Empty; // name of the object in Navisworks

        [Required]
        public string Type { get; set; } = string.Empty; // type of the object (e.g., wall, door, etc.)
    }
}
